using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DecodeTietoEI.Zad
{
    class Zad41
    {
        public int result=0;
        string input;
        public void Run()
        {
            Fill();
            for (int i = 0; i < input.Length - 5; i++)
            {
                if (IsPalindrom(input.Substring(i, 5)))
                    result++;
            }
        }
        bool IsPalindrom(string n)
        {
            string str = n.ToString();
            for (int i = 0; i < str.Length; i++)
            {
                int end = str.Length - i - 1;
                if (i == end)
                {
                    break;
                }
                if (str[i] != str[end])
                    return false;
            }
            return true;
        }
        void Fill()
        {
            input = @"KAXOJWRHGCMNUPONJPDUVTCKJLFZZTZBJCWFRMRKJPLGNAIUMDSXHRWSUOQJIEHKXZDWANYYUSHT
LKLGDIUMEUCUIMQFUGZDJZMYAHDXUPRFBHGIEKLMHDTOTDBSKBTWMEFKPFKYNNMQMBVJVXQTWWJJ
IJFJTJIZBLRMQBAPNAFIDNOLDXNCLSJHLXRFJZDVFEZSQVDDAZDZYSUCAAVUEJFRIHCZGGRONYJT
TUNRAFVOECXFHGPJNQGQTIBZTIJFCUWLWKFLPZOQSLYFOKGQEWGEFJNLLUCYJRPQKUZNKYCJGRVF
FYIASIMWTVJQRDQZKRTHYWZQSTZVRUZKKSWJRKUZTXMPDCNHWDDIVIFQHAFWDREZEXJCIQETKZUW
RZYAMAQJCTUIJFKADHFSVJAVJDKGDOINRNWTJMDQDZDIKUFXELAJOFTYTSIDXGIVFHDBTLGUEQUZ
ESMSECAYBGIJKMKDRMLTDOBWDKYYVHJYIWZFUCUPCAGSNQLFRYGBURUZKVBIJEOJZKUPWBJEMFQB
EORKXXERZVCACIFAVBFTRJIYSSQVCJIDSCIRUOYTZNCUQMOYGJBFHORCCCPOGEWEFZHJKJYTYQTB
TYUMNAKIRZUEYABBPGDJGRWLLYGVIUWHYFFISUNVDGXXJZDYEELPYSZDJZUNHBNMCJVMRRTVPVKE
LRKWQOWTUANONVWXYALFXJJKWKYHKBKZFANTVURLIDLRIDXPKMZRJSXSIWWUHRGOWVUNVRYUKDPI
FMUPMXLACENZBRBJIWCNCCEWIIYMJDYGKVMFJOXEQRYBBDCVEXRNJOAFXSRJQGWVBKEHVMILWYUJ
FPGFEDAAETDJMRPNNETXOHFGQLWRSSNXNMHNDWJCDXIDHHQXJAJUKITOEUVFEZJRXAJNNFFQVPOZ
AAEMRALFSUIHMQNXJJMJMPIVTTTXVCHQTFAOFJSDGMGITAMHXUGKKXKJGSXVEPXTMHJKZMGRXMKP
ITYQILXLAWBCRXHRGGHGXTVYTBIODQRJQDGZONKXRHBNYADHHJKSRDVFSCJSXSULMRTYRQVLDDXA
ZUARDYRBNECGJTKFWCRUOQUEGRAVVIZVJRMXIWZGROYZRJKHYTDSYSIOQMHSPFSSDLOTCKVTAOVK
KHOQGUYTBQANEJRAAADRVBALCDUAHGRNJVJNBLZJURUTGNRPZBBKRFOPMTCATBVHKWHHNXPZROXR
YKWFZCPVFQPGOSXBSIDTPSOWEKPADEMUABPEVJAHLNPOGJESJESYHONHINFLCTPFIVRZSUOWUCCT
BXWFKCIZEVJHYUEXEDUYSDZOIBGWTOHIYSOSELZBWUEKPMWECTZULEYMKAPIHVFBXSXRRYPTKKOI
VRIPHQNQKSCOPCSWVKPXAEQDNVPKBPPLYNXKIBCLVZGVEWVZQTUQYAZOUDDRTFWWVVKPGTEQPKNO
MOLDTZQRJHOMMDGJXNXYBQXEEVPMNDPTPVWZCLRZIEYYVNUTGIEGPGFXPBUQSETVHARUALXEOACW
VJBLDUFYABLXCDGRBIQWAZYIKMPBBQDBZZINKAFJWALFEOCCHSPWVWHWFTPQHOOYCUJGVPLIOPSP
YXKGFVXOMHDGOPVFBQKVSQDXQBMEMQBNPNHZEVTUOJOCDWUJIVHQVSLBABQDEUFXTTVMKGDHMNYQ
SZLPHHZUGRKHRDAABOUYRIZKMSFRWVXBFCHWBGESMOREFXZKFAPPQSLRBFTFHSZGDEDRHVUFEOJG
NMNIAAMWFYWOBFAVZQCTGTXAERJYNNFOSBNKFILSRCRTVYPSAPXQDWDCLZLKIOQYUPQZNQTHAQFY
OURSJAXQELWGIKKZVDJDZDBVHPWWKZHFFQLLJNWLWGFAVCDGBUCGEEHBXJVMMMJOGFQAJTDFWJNO
UJUXTLURFNQTYYCEJNMPXHAIMGKEURNYCFMWEZAINTVRCVLQFBYHNRBPYLZYRCSNFWVONYLXFSGN
TOZPHQHXSORNMZYZIMIHSNKDX";
            input = input.Replace("\r\n", string.Empty);

        }
    }
}
